=== safernandez9/Lenguaje-de-Marcas/Tema 4 Validación XML Schema/Ejercicios/Tarea 3/UD4_T3A_SaulFernandezSalgado.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="garderia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="neno" maxOccurs="50" type="tipoNeno"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="tipoNeno">
    <xs:sequence>
      <xs:element name="nome">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="80"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="sexo">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="H"/>
            <xs:enumeration value="M"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="dataNacemento" type="xs:date"/>
      <xs:element name="peso">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="altura" type="xs:unsignedByte"/>
      <xs:element name="vacunas" type="xs:boolean"/>
      <xs:element name="idade">
        <xs:complexType>
          <xs:attribute name="anos" type="xs:byte" use="required"/>
          <xs:attribute name="meses" type="xs:byte" use="required"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="contacto" maxOccurs="4">
        <xs:complexType>
          <xs:attribute name="relación" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="nai"/>
                <xs:enumeration value="pai"/>
                <xs:enumeration value="avó"/>
                <xs:enumeration value="avóa"/>
                <xs:enumeration value="titor"/>
                <xs:enumeration value="outra"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:element name="telefono">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="\d{9}"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="numeroExpedente" type="xs:unsignedShort" use="required"/>
    <xs:attribute name="codigo" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="[PM][3-7]{2}(-\d{3})?"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== safernandez9/Lenguaje-de-Marcas/Tema 4 Validación XML Schema/Ejercicios/Tarea 3/UD4_T3A_SaulFernandezSalgado.xml
<?xml version="1.0"?>
<garderia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="UD4_T3A_SaulFernandezSalgado.xsd">
  <neno numeroExpedente="323" codigo="P44-323">
    <nome>Pablo</nome>
    <sexo>H</sexo>
    <dataNacemento>2020-05-15</dataNacemento>
    <peso>15.5</peso>
    <altura>63</altura>
    <vacunas>true</vacunas>
    <idade anos="3" meses="6"/>
    <contacto relación="nai">
      <telefono>123456789</telefono>
    </contacto>
    <contacto relación="pai">
      <telefono>987654321</telefono>
    </contacto>
  </neno>
</garderia>
