=== safernandez9/Lenguaje-de-Marcas/Tema 3 Validación DTD/EjsRepaso/Ejercicio9.dtd
<!ELEMENT Informe (Descripcion?, Seguro+, FechaInforme)>
<!ELEMENT FechaInforme EMPTY>
<!ELEMENT Seguro (Numero, (ClienteP | ClienteE))>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT ClienteP (#PCDATA)>
<!ELEMENT ClienteE (#PCDATA)>
<!ATTLIST Seguro tipo (Edificio | Contenido) #REQUIRED>
<!ATTLIST FechaInforme FechaInicio CDATA #REQUIRED>
<!ATTLIST FechaInforme FechaFin CDATA #IMPLIED>

=== safernandez9/Lenguaje-de-Marcas/Tema 3 Validación DTD/EjsRepaso/Ejercicio10.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Informe SYSTEM "Ejercicio9.dtd">
<Informe>
 <Descripcion>Informe mensual de seguros de clientes registrados.</Descripcion>

  <Seguro tipo="Edificio">
    <Numero>SEG-001</Numero>
  <ClienteP>Juan Pérez</ClienteP>
  </Seguro>

  <Seguro tipo="Contenido">
    <Numero>SEG-002</Numero>
    <ClienteE>Construcciones Méxicas S.A. de C.V.</ClienteE>
  </Seguro>

  <Seguro tipo="Contenido">
    <Numero>SEG-003</Numero>
    <ClienteP>Ana García</ClienteP>
  </Seguro>

  <FechaInforme FechaInicio="2025-01-01" FechaFin="2025-01-31"/>
</Informe>
