=== safernandez9/Lenguaje-de-Marcas/Tema 3 Validación DTD/Ejercicios/Tarea 7/Tarea7B.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Informe (Descripcion*, Seguro+, FechaInforme)>
<!ELEMENT FechaInforme EMPTY>
<!ELEMENT Seguro (Numero, (Cliente-Personal | Cliente-Empresa))>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT Cliente-Personal (#PCDATA)>
<!ELEMENT Cliente-Empresa (#PCDATA)>
<!ATTLIST Seguro tipo (Edificio | Contenido) #REQUIRED>
<!ATTLIST FechaInforme FechaInicio CDATA #REQUIRED
                        FechaFin CDATA #IMPLIED>

=== safernandez9/Lenguaje-de-Marcas/Tema 3 Validación DTD/Ejercicios/Tarea 7/Tarea 7B.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE Informe SYSTEM "Tarea7B.dtd">
<Informe>
  <Descripcion>Informe de seguros de cliente VIP.</Descripcion>
  <Seguro tipo="Edificio">
    <Numero>12345</Numero>
    <Cliente-Personal>Juan PÃ©rez</Cliente-Personal>
  </Seguro>

  <Seguro tipo="Contenido">
    <Numero>67890</Numero>
    <Cliente-Empresa>Empresa S.A.</Cliente-Empresa>
  </Seguro>

  <FechaInforme FechaInicio="2025-01-01" FechaFin="2025-12-31"/>
</Informe>
